server:
  port: 8090

spring:
  application:
    name: servicio-gateway-server
  
  cloud:
    gateway:
      routes:
        - id: servicio-products
          uri: lb://servicio-products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2           
        - id: servicio-clients
          uri: lb://servicio-clients
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=2
        - id: servicio-catagregate
          uri: lb://servicio-catagregate
          predicates:
            - Path=/api/catalogue/**
          filters:
            - StripPrefix=2
        - id: servicio-users
          uri: lb://servicio-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: servicio-orders
          uri: lb://servicio-orders
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
